version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: state-machine_postgres # hostName
    restart: always
    environment:
      POSTGRES_DB: mydb # Maintenance Database:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5455:5432" # 5432 (Docker daxili şəbəkəsində konteynerlər bir-biri ilə daxili port üzərindən danışır.
      # 5455 sizin lokal kompüter üçün olan xarici portdur.
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: state-machine_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5059:80"      # PGAdmin brauzer portu

volumes:
  postgres_data: