spring:
  datasource:
    url: jdbc:postgresql://localhost:5455/mydb
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080